config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'home#index'
  
  get 'history', to: 'home#history'
  
  get 'amenity', to: 'home#amenity'

  get 'migration', to: 'home#migration'
  
  get 'comps', to: 'home#comps'
  
  get 'apartment', to: 'home#apartment'
  
  get 'inventory', to: 'home#inventory'
  
  get 'infrastructure', to: 'home#infrastructure'
  
  get 'transit', to: 'home#transit'
  
  get 'timeseries', to: 'home#timeseries'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/amenity.html.erb
<h1>24/7 Dynamic Amenities</h2>
    <p>The final piece of the puzzle - tying together River North, Restaurant Row and the Milwaukee Corridor</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    <div id='image-caption'>
        <p>Interactive Guide: To view detailed area amenities, mouse-in to zoom and press control to rotate</p>
    </div>
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjsvs21w60gjk1fmovfg87xhb',
          center: [-87.636127, 41.892699],
          zoom: 13.6,
          maxZoom: 17.0,
          minZoom: 13.5,
        });
        
        var framesPerSecond = 15; 
        var initialOpacity = 1
        var opacity = initialOpacity;
        var initialRadius = 10;
        var radius = initialRadius;
        var maxRadius = 50;
        
        map.on('load', function () {
        
            // Add a source and layer displaying a point which will be animated in a circle.
            map.addSource('point', {
                "type": "geojson",
                "data": {
                    "type": "Point",
                    "coordinates": [
                        -87.646164, 41.894611
                    ]
                }
            });
        
            map.addLayer({
                "id": "point",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-radius-transition": {duration: 0},
                    "circle-opacity-transition": {duration: 0},
                    "circle-color": "#ffffff"
                }
            });
        
            map.addLayer({
                "id": "point1",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-color": "#007cbf"
                }
            });
        
            map.addControl(new mapboxgl.NavigationControl());    

        
            function animateMarker(timestamp) {
                setTimeout(function(){
                    requestAnimationFrame(animateMarker);
        
                    radius += (maxRadius - radius) / framesPerSecond;
                    opacity -= ( .9 / framesPerSecond );
        
                    map.setPaintProperty('point', 'circle-radius', radius);
                    map.setPaintProperty('point', 'circle-opacity', opacity);
        
                    if (opacity <= 0) {
                        radius = initialRadius;
                        opacity = initialOpacity;
                    } 
        
                }, 1000 / framesPerSecond);
                
            }
        
            // Start the animation.
            animateMarker(0);
        });
        
        
        </script>

app/views/home/apartment.html.erb
<h1>Premier Apartments</h2>
    <p>A new riverfront enclave situated among the City's most desirable submarkets</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
    <div id='image-caption'>
        <p>Interactive Guide: Mouse-in to view residential project names and effective rental rates</p>
    </div>
    
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjszdfg6e33t21fo3pxkicd6g',
          center: [-87.645762, 41.890340],
          zoom: 12.5,
          maxZoom: 15.0,
          minZoom: 12.5,
        });
        
        var framesPerSecond = 15; 
        var initialOpacity = 1
        var opacity = initialOpacity;
        var initialRadius = 10;
        var radius = initialRadius;
        var maxRadius = 50;
        
        map.on('load', function () {
        
            // Add a source and layer displaying a point which will be animated in a circle.
            map.addSource('point', {
                "type": "geojson",
                "data": {
                    "type": "Point",
                    "coordinates": [
                        -87.646164, 41.894611
                    ]
                }
            });
        
            map.addLayer({
                "id": "point",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-radius-transition": {duration: 0},
                    "circle-opacity-transition": {duration: 0},
                    "circle-color": "#ffffff"
                }
            });
        
            map.addLayer({
                "id": "point1",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-color": "#007cbf"
                }
            });
        
        
            function animateMarker(timestamp) {
                setTimeout(function(){
                    requestAnimationFrame(animateMarker);
        
                    radius += (maxRadius - radius) / framesPerSecond;
                    opacity -= ( .9 / framesPerSecond );
        
                    map.setPaintProperty('point', 'circle-radius', radius);
                    map.setPaintProperty('point', 'circle-opacity', opacity);
        
                    if (opacity <= 0) {
                        radius = initialRadius;
                        opacity = initialOpacity;
                    } 
        
                }, 1000 / framesPerSecond);
                
            }
        
            // Start the animation.
            animateMarker(0);
        });

        </script>
    
    

app/views/home/comps.html.erb
<h1>Comps in Perspective</h2>
    <p>A natural extension of the City's new office and residential epicenter - the confluence of the River</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
        <div id='image-caption'>
            <p>Interactive Guide: Mouse-in to view 3D site massing in perspective with notable office buildings</p>
        </div>
        
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjst6uv4wb7ii1fs8z4gbrnaw',
          center: [-87.638309, 41.886469],
          zoom: 13.5,
          pitch: 45,
          maxZoom: 14.5,
          minZoom: 12.5,
        });
        
        function rotateCamera(timestamp) {
            // clamp the rotation between 0 -360 degrees
            // Divide timestamp by 100 to slow rotation to ~10 degrees / sec
            map.rotateTo((timestamp / 100) % 360, {duration: 0});
            // Request the next frame of the animation.
            requestAnimationFrame(rotateCamera);
        }

        map.on('load', function () {
            // Start the animation.
            rotateCamera(0);

            // Add 3d buildings and remove label layers to enhance the map
            var layers = map.getStyle().layers;
            for (var i = 0; i < layers.length; i++) {
            if (layers[i].type === 'symbol' && layers[i].layout['text-field']) {
            // remove text labels
            map.removeLayer(layers[i].id);
            }
        }
 
        map.addLayer({
            'id': '3d-buildings',
            'source': 'composite',
            'source-layer': 'building',
            'filter': ['==', 'extrude', 'true'],
            'type': 'fill-extrusion',
            'minzoom': 15,
            'paint': {
                'fill-extrusion-color': '#aaa',
                // use an 'interpolate' expression to add a smooth transition effect to the
                // buildings as the user zooms in
                'fill-extrusion-height': [
                "interpolate", ["linear"], ["zoom"],
                15, 0,
                15.05, ["get", "height"]
                ],
                'fill-extrusion-base': [
                "interpolate", ["linear"], ["zoom"],
                15, 0,
                15.05, ["get", "min_height"]
                ],
                'fill-extrusion-opacity': .6
                }
            });
        });
        
        map.addControl(new mapboxgl.NavigationControl());
        
        
        map.addSource("source_circle_500", {
    "type": "geojson",
    "data": {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [-85.1392, 41.0804]
            }
        }]
    }
});

map.addLayer({
    "id": "circle500",
    "type": "circle",
    "source": "source_circle_500",
    "layout": {
        "visibility": "none"
    },
    "paint": {
        "circle-radius": 804672,
        "circle-color": "#5b94c6",
        "circle-opacity": 0.6
    }
});
        
        
        
</script>

app/views/home/history.html.erb
<h1>Natural Path of Growth</h1>
    <p>Dynamic 24/7 submarkets expanding around the site for office and residential</p>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe src="https://player.vimeo.com/video/322144032?autoplay=1&loop=1" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow=autoplay></iframe>
        </div>
        
        <div id='image-caption'>
            <p>Interactive Guide: To view timelapse in full screen, press arrow icon at bottom right of video player</p>
        </div>

app/views/home/index.html.erb
<h1>Surrounded by Density</h1>
    <p>30-acre infill riverfront site, artifically restricted from development by zoning for +30 years</p>
        <div class="embed-responsive embed-responsive-16by9">
          <iframe src="https://player.vimeo.com/video/321771566?autoplay=1&loop=1" width="640" height="360" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen allow=autoplay></iframe>
        </div>
        
        <div id='image-caption'>
            <p>*Aerial view south along the future North Branch Transitway + Jefferson Boulevard</p>
        </div>

app/views/home/infrastructure.html.erb
<h1>New Infrastructure</h2>
    <p>Transformational projects to strengthen accessibility and enable a transit-oriented lifestyle</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
    <div id='image-caption'>
        <p>Interactive Guide: Mouse-out to view full extent of BRT, Transitway and Riverwalk connections</p>
    </div>
    
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjs9bp4va02fw1fnl14pj9xof',
          center: [-87.644401, 41.891133],
          zoom: 14.4,
          maxZoom: 15.0,
          minZoom: 12.5,
        });
        
        var framesPerSecond = 15; 
        var initialOpacity = 1
        var opacity = initialOpacity;
        var initialRadius = 10;
        var radius = initialRadius;
        var maxRadius = 50;
        
        map.on('load', function () {
        
            // Add a source and layer displaying a point which will be animated in a circle.
            map.addSource('point', {
                "type": "geojson",
                "data": {
                    "type": "Point",
                    "coordinates": [
                        -87.646164, 41.894611
                    ]
                }
            });
        
            map.addLayer({
                "id": "point",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-radius-transition": {duration: 0},
                    "circle-opacity-transition": {duration: 0},
                    "circle-color": "#ffffff"
                }
            });
        
            map.addLayer({
                "id": "point1",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-color": "#007cbf"
                }
            });
        
        
            function animateMarker(timestamp) {
                setTimeout(function(){
                    requestAnimationFrame(animateMarker);
        
                    radius += (maxRadius - radius) / framesPerSecond;
                    opacity -= ( .9 / framesPerSecond );
        
                    map.setPaintProperty('point', 'circle-radius', radius);
                    map.setPaintProperty('point', 'circle-opacity', opacity);
        
                    if (opacity <= 0) {
                        radius = initialRadius;
                        opacity = initialOpacity;
                    } 
        
                }, 1000 / framesPerSecond);
                
            }
        
            // Start the animation.
            animateMarker(0);
        });

        </script>
    
    

app/views/home/inventory.html.erb
<h1>Office Inventory</h2>
    <p>Statement about new sites</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
    <div id='image-caption'>
        <p>Interactive Guide: Mouse-in to view River District parcels relative to CBD migration</p>
    </div>
    
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjt8v9o592r3s1fmggvf30oak',
          center: [-87.645762, 41.890340],
          zoom: 12.5,
          maxZoom: 15.0,
          minZoom: 12.5,
        });
        
        var framesPerSecond = 15; 
        var initialOpacity = 1
        var opacity = initialOpacity;
        var initialRadius = 10;
        var radius = initialRadius;
        var maxRadius = 50;
        
        map.on('load', function () {
        
            // Add a source and layer displaying a point which will be animated in a circle.
            map.addSource('point', {
                "type": "geojson",
                "data": {
                    "type": "Point",
                    "coordinates": [
                        -87.646164, 41.894611
                    ]
                }
            });
        
            map.addLayer({
                "id": "point",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-radius-transition": {duration: 0},
                    "circle-opacity-transition": {duration: 0},
                    "circle-color": "#ffffff"
                }
            });
        
            map.addLayer({
                "id": "point1",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-color": "#007cbf"
                }
            });
        
        
            function animateMarker(timestamp) {
                setTimeout(function(){
                    requestAnimationFrame(animateMarker);
        
                    radius += (maxRadius - radius) / framesPerSecond;
                    opacity -= ( .9 / framesPerSecond );
        
                    map.setPaintProperty('point', 'circle-radius', radius);
                    map.setPaintProperty('point', 'circle-opacity', opacity);
        
                    if (opacity <= 0) {
                        radius = initialRadius;
                        opacity = initialOpacity;
                    } 
        
                }, 1000 / framesPerSecond);
                
            }
        
            // Start the animation.
            animateMarker(0);
        });

        </script>
    
    

app/views/home/migration.html.erb
<h1>Suburban Migration</h2>
    <p>70% of Suburban Migrations Locate in West Loop (55%), River North(17%), Fulton Market(8%)</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
    <div id='image-caption'>
        <p>Interactive Guide: Mouse-in to view River District parcels relative to CBD migration</p>
    </div>
    
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjt7gnxc401061foks0a3v50w',
          center: [-87.645762, 41.890340],
          zoom: 12.5,
          maxZoom: 15.0,
          minZoom: 12.5,
        });
        
        var framesPerSecond = 15; 
        var initialOpacity = 1
        var opacity = initialOpacity;
        var initialRadius = 10;
        var radius = initialRadius;
        var maxRadius = 50;
        
        map.on('load', function () {
        
            // Add a source and layer displaying a point which will be animated in a circle.
            map.addSource('point', {
                "type": "geojson",
                "data": {
                    "type": "Point",
                    "coordinates": [
                        -87.646164, 41.894611
                    ]
                }
            });
        
            map.addLayer({
                "id": "point",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-radius-transition": {duration: 0},
                    "circle-opacity-transition": {duration: 0},
                    "circle-color": "#ffffff"
                }
            });
        
            map.addLayer({
                "id": "point1",
                "source": "point",
                "type": "circle",
                "paint": {
                    "circle-radius": initialRadius,
                    "circle-color": "#007cbf"
                }
            });
        
        
            function animateMarker(timestamp) {
                setTimeout(function(){
                    requestAnimationFrame(animateMarker);
        
                    radius += (maxRadius - radius) / framesPerSecond;
                    opacity -= ( .9 / framesPerSecond );
        
                    map.setPaintProperty('point', 'circle-radius', radius);
                    map.setPaintProperty('point', 'circle-opacity', opacity);
        
                    if (opacity <= 0) {
                        radius = initialRadius;
                        opacity = initialOpacity;
                    } 
        
                }, 1000 / framesPerSecond);
                
            }
        
            // Start the animation.
            animateMarker(0);
        });

        </script>
    
    

app/views/home/office.html.erb
<h1>Office in Perspective</h2>
    <p>A natural extension of the City's new office epicenter - the confluence of the River</p>
    <div id="map-container">
        <div id='map'></div>
    </div>
    
        <div id='image-caption'>
            <p>Interactive Guide: Mouse-in to view 3D site massing in perspective with notable office buildings</p>
        </div>
        
        <script>
        mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
        const map = new mapboxgl.Map({
          container: 'map',
          style: 'mapbox://styles/mpotter/cjst6uv4wb7ii1fs8z4gbrnaw',
          center: [-87.638309, 41.886469],
          zoom: 13.5,
          pitch: 45,
          maxZoom: 14.5,
          minZoom: 12.5,
        });
        
        function rotateCamera(timestamp) {
            // clamp the rotation between 0 -360 degrees
            // Divide timestamp by 100 to slow rotation to ~10 degrees / sec
            map.rotateTo((timestamp / 100) % 360, {duration: 0});
            // Request the next frame of the animation.
            requestAnimationFrame(rotateCamera);
        }

        map.on('load', function () {
            // Start the animation.
            rotateCamera(0);

            // Add 3d buildings and remove label layers to enhance the map
            var layers = map.getStyle().layers;
            for (var i = 0; i < layers.length; i++) {
            if (layers[i].type === 'symbol' && layers[i].layout['text-field']) {
            // remove text labels
            map.removeLayer(layers[i].id);
            }
        }
 
        map.addLayer({
            'id': '3d-buildings',
            'source': 'composite',
            'source-layer': 'building',
            'filter': ['==', 'extrude', 'true'],
            'type': 'fill-extrusion',
            'minzoom': 15,
            'paint': {
                'fill-extrusion-color': '#aaa',
                // use an 'interpolate' expression to add a smooth transition effect to the
                // buildings as the user zooms in
                'fill-extrusion-height': [
                "interpolate", ["linear"], ["zoom"],
                15, 0,
                15.05, ["get", "height"]
                ],
                'fill-extrusion-base': [
                "interpolate", ["linear"], ["zoom"],
                15, 0,
                15.05, ["get", "min_height"]
                ],
                'fill-extrusion-opacity': .6
                }
            });
        });
        
        map.addControl(new mapboxgl.NavigationControl());
        
        
        map.addSource("source_circle_500", {
    "type": "geojson",
    "data": {
        "type": "FeatureCollection",
        "features": [{
            "type": "Feature",
            "geometry": {
                "type": "Point",
                "coordinates": [-85.1392, 41.0804]
            }
        }]
    }
});

map.addLayer({
    "id": "circle500",
    "type": "circle",
    "source": "source_circle_500",
    "layout": {
        "visibility": "none"
    },
    "paint": {
        "circle-radius": 804672,
        "circle-color": "#5b94c6",
        "circle-opacity": 0.6
    }
});
        
        
        
</script>

app/views/home/timeseries.html.erb
<h1>20 Years in the Making</h2>
    <p>Click on Slider to Navigate Supply Across Time</p>

<body>

<div id='map'></div>

<div class='map-overlay top'>
    <div class='map-overlay-inner'>
        <h2>Significant earthquakes in 2015</h2>
        <label id='year'></label>
        <input id='slider' type='range' min='2000' max='2011' step='1' value='2005' />
    </div>
    <div class='map-overlay-inner'>
        <div id='legend' class='legend'>
            <div class='bar'></div>
            <div>Magnitude (m)</div>
        </div>
    </div>
</div>

<script src="https://d3js.org/d3.v5.min.js" charset='utf-8'></script>
<script>
mapboxgl.accessToken = 'pk.eyJ1IjoibXBvdHRlciIsImEiOiJjajAxZGltM3UwNjF2MzJsczVnN3R2eTNnIn0._Sj0HRLt8VTQGTojMWYFfQ';
var map = new mapboxgl.Map({
    container: 'map',
    style: 'mapbox://styles/mpotter/cjszdfg6e33t21fo3pxkicd6g',
    center: [-87.645762, 41.890340],
    zoom: 12.5
});

var years = [
    2000,
    2001,
    2002,
    2003,
    2004,
    2005,
    2006,
    2007,
    2008,
    2009,
    2010,
    2011
];

function filterBy(year) {

    var filters = ['==', 'year', year];
    map.setFilter('earthquake-circles', filters);
    map.setFilter('earthquake-labels', filters);

    // Set the label to the month
    document.getElementById('year').textContent = years[year];
}

map.on('load', function() {

    // Data courtesy of http://earthquake.usgs.gov/
    // Query for significant earthquakes in 2015 URL request looked like this:
    // http://earthquake.usgs.gov/fdsnws/event/1/query
    //    ?format=geojson
    //    &starttime=2015-01-01
    //    &endtime=2015-12-31
    //    &minmagnitude=6'
    //
    // Here we're using d3 to help us make the ajax request but you can use
    // Any request method (library or otherwise) you wish.
    d3.json('https://s3.us-east-2.amazonaws.com/tribune37/ChicagoAllDevelopment.geojson', function(err, data) {
        if (err) throw err;

        // Create a month property value based on time
        // used to filter against.
        data.features = data.features.map(function(d) {
            d.properties.year = new Date(d.properties.DateTime).getFullYear();
            return d;
        });

        map.addSource('earthquakes', {
            'type': 'geojson',
            data: data
        });

        map.addLayer({
            'id': 'earthquake-circles',
            'type': 'circle',
            'source': 'earthquakes',
            'paint': {
                'circle-color': [
                    'interpolate',
                    ['linear'],
                    ['get', 'GFA'],
                    0, '#FCA107',
                    3000000, '#7F3121'
                ],
                'circle-opacity': 0.75,
                'circle-radius': [
                    'interpolate',
                    ['linear'],
                    ['get', 'GFA'],
                    0, 20,
                    3000000, 40
                ]
            }
        });

        map.addLayer({
            'id': 'earthquake-labels',
            'type': 'symbol',
            'source': 'earthquakes',
            'layout': {
                'text-field': ['concat', ['to-string', ['get', 'GFA']], 'm'],
                'text-font': ['Open Sans Bold', 'Arial Unicode MS Bold'],
                'text-size': 12
            },
            'paint': {
                'text-color': 'rgba(0,0,0,0.5)'
            }
        });

        // Set filter to first month of the year
        // 0 = January
        filterBy(2005);

        document.getElementById('slider').addEventListener('input', function(e) {
            var year = parseInt(e.target.value, 10);
            filterBy(year);
        });
    });
});
</script>

</body>

app/views/home/transit.html.erb
<h1>Transit Maps</h1>




<div class="owl-carousel owl-theme">
  <div><%= link_to image_tag("Education.jpg", alt: "Education Map", class: "img-responsive")%></div>
  <div><%= link_to image_tag("Demographics.jpg", alt: "Demographics Map", class: "img-responsive")%></div>
  <div><img src="http://lorempixel.com/g/800/600/nightlife"></div>
  <div><img src="http://lorempixel.com/g/800/600/fashion"></div>
  <div><img src="http://lorempixel.com/g/800/600/nightlife"></div>
  <div><%= link_to image_tag("Cultural.jpg", alt: "Cultural Map", class: "img-responsive")%></div>
</div>
 

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script type="text/javascript" src="https://owlcarousel2.github.io/OwlCarousel2/assets/owlcarousel/owl.carousel.js"></script>

<script type="text/javascript">
$('.owl-carousel').owlCarousel({
   singleItem: true,
   loop:true,
   autoplay: true,
   margin:10,
   nav:true,
   responsive:{
     0:{
       items:1
     },
     600:{
       items:3
     },
     1000:{
       items:5
     }
   }
 });
</script>

app/views/home/transitway.html.erb
<h1>Add vimeo shuttle video</h1>

app/views/home/zoning.html.erb
<div id="map-container">
    <%=image_tag("https://s3.us-east-2.amazonaws.com/tribune37/ChicagoZoning.gif", class: "img-responsive") %>
    <h5 class="image-caption">As Chicago's cententral core expands, new zoning is reshaping urban renewal on revitalized waterfront</h5>
</div>

app/views/layouts/_footer.html.erb
<footer class="container footer">
  <nav class="navbar d-flex">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a <%= link_to "Home", root_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "History", history_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Amenities", amenity_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Migration", migration_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Comps", comps_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Inventory", inventory_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Apartment", apartment_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Infrastructure", infrastructure_path %> </a></li>
        <li class="breadcrumb-item"><a <%= link_to "Time Series", timeseries_path %> </a></li>
      </ol>
    </nav>
    
    <a href = "http://riversideid.com/" target="_blank">
      <font color="black"> &copy; 2018 RIVERSIDE </font>
    
  </nav>
    
</footer>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light d-flex">
  <div class="container">
    <div class="logo">
      <a class="navbar-brand" href="#">
        <%= image_tag("RIVERIDELOGO.jpg", {:style => "width:100px;"}) %>
      </a>
    </div>
    <div class="user-section">
      <%= link_to "Data-Driven Development Portal", root_path, class: "navbar-brand", id: "logo-right" %>
    </div>
  </div>
</nav>